### ISSUE TITLE
Request: Create function that will take a string that is a sentence and will insert new line characters into string at a designated length

### ISSUE THREAD

**Issue by dpashouwer** [tntp/tntpr#11]
**_Function Request:_**

Function that will take a string that is a sentence and capped length as arguments. Then the 
function will add new lines between appropriate words (length < capped length).

Example:
With the string "My Child Currently Attends A High Quality School" and capped length = 17, it would become

"My Child\nCurrently Attends\nA High Quality\nSchool"

so when it's printed it becomes
"""
My Child
Currently
Attends
A High Quality
School
"""

Note: Purpose is for appropriate spacing in ggplot2 graphs.

**Comment by sfirke** [comment]
Good idea.  There are some starting points [on StackOverflow](https://stackoverflow.com/questions/7367138/text-wrap-for-plot-titles), I'm asking around the web too.

**Comment by sfirke** [comment]
will `scales::wrap_format` do?

**Comment by dpashouwer** [comment]
Yes! wrap_format is exactly what I need. Thanks!
