### ISSUE TITLE
Add new plotting features to vignette

### ISSUE THREAD

**Issue by sfirke** [tntp/tntpr#12]
@dpashouwer I think you added `theme_tntp_2018()` and `scale_color_tntp` to the package but I don't see them mentioned in the vignette.  Could you add them to the examples and re-knit that file?  I'd like to point Melissa to them (we are making charts).

**Comment by dpashouwer** [comment]
Added general updates to the Introduction vignette. Working on a "Creating TNTP-style ggplot2 Graphs" vignette that will go more in depth.

**Comment by sfirke** [comment]
Nice!  Thanks.  If you want to be fancy in the future, you can put "closes #12" in the commit message description (the secondary part of the commit message) and it will close this issue automatically, along with a link to the commit that closed it.
